### PR TITLE
Added an example console app that uses ABP (based on MVC template)

### PR DESCRIPTION
**Pull request by natiki**
Hi,

I created AbpHangfireConsoleApp that can be used a starting point when people want to make a console application based on ABP. It uses the ABP bootstrapper, modules etc. so it is almost copy and go.

The Readme.md has more details about other bits and pieces it does.

Adding a console app template would be nice to do for those that only want a bare minimum application.

### CODE REVIEW

**Comment by ismcagdas** [comment]
@natiki thanks for your contribution.
I have downloaded and tried to run the project but faced some problems.

There is no migration on the solution, so when I tried to run "Update-Database" command, it says something like this.

image

Then, I have added a new migration named test like this:

image

After running "Update-Database" command created the DB. But, when I run the console app, it says there is already a table named "HangFire.Server" because hangfire tries to create it's own tables when the app starts.

If I delete this "Hanfire.Server" table manually, then I get an "access-denied" error because I haven't run Visual Studio in Administrator mode, so it doesn't have right to start hangfire on "http://127.0.0.1:8111". I think it will be good to write this into Readme file.

What is your comment about migration/Hanfire.Server table ? Is there anything I was supposed to do before running the project ?

**Comment by natiki** [comment]
Hi @ismcagdas,

I have updated the installation. Basically to say that all you need to do is run up the application while Visual Studio is in administrator mode. That will create the Hangfire tables for you. The only reason the migrations are there is for completeness so that adding migrations can be easily done.

**Comment by natiki** [comment]
@ismcagdas Amended Program.cs to be clearer. I will run a `Add-Migration InitialCreate –IgnoreChanges` and push that on Monday. The table I was using is actually a Hangfire one so all that is needed is to start with an empty migration.

**Comment by natiki** [comment]
@ismcagdas Added the initial migration should you should be all good to go.

**Comment by ismcagdas** [comment]
@natiki awesome 😄

**Pull request merged**
