### PR TITLE
Add GraphQL sample.

### PR DESCRIPTION
**Pull request by maliming**
# The example is based on the following article

 See: https://medium.com/volosoft/building-graphql-apis-with-asp-net-core-419b32a5305b

 ## Get Started

 * Modify the database connection string as needed, then perform the migration.
* Launch the Hotel.Web.Host project, browse http://localhost:21021/ui/playground
* Enter the expression to execute the query.

 Input:
```
query TestQuery {
  reservations (roomAllowedSmoking:false, roomStatus: AVAILABLE){
    id
    checkinDate
    checkoutDate
    guest {
      id
      name
      registerDate
    }
    room {
      id
      name
      number
      allowedSmoking
      status
    }
  }
}
```

 Output:
```
{
  "data": {
    "reservations": [
      {
        "id": 1,
        "checkinDate": "2019-07-14",
        "checkoutDate": "2019-07-19",
        "guest": null,
        "room": null
      },
      {
        "id": 2,
        "checkinDate": "2019-07-15",
        "checkoutDate": "2019-07-20",
        "guest": null,
        "room": null
      }
    ]
  }
}
```
For more details, please refer to the above article and the documentation of graphql.

### CODE REVIEW

**Comment by Mehranh** [comment]
@maliming  I read your code 
Please see HotelQuery  class.
In this class  InternalResolve method should return Queryable<Reservation> instead of List<Reservation>.

Kindest Regards

**Comment by maliming** [comment]
@Mehranh 
Why return Iqueryable? It can't work outside the unit of work.

I am not particularly familiar with this, but I tested it to query the data normally.

**Comment by Mehranh** [comment]
I think the benefit of using GraphQL is that the client determine which data should get from database.

By this solution you get data from database and after that client select his own data.
Also, you can see in the article that you mentioned in one case it returns Queryble.

I know it can't work outside the unit of work. But I guessed maybe there is a solution.

**Comment by ismcagdas** [comment]
@Mehranh unfortunately it doesn't work that way.

**Comment by Mehranh** [comment]
@ismcagdas it means you won't create a way to solve this issue in next updates?

**Comment by ismcagdas** [comment]
No. The used library doesn't support such a usage.

**Pull request merged**
