### PR TITLE
Alter IdentityServerDemo to .net core 2.0

### PR DESCRIPTION
**Pull request by parallelbgls**
Please focus on the third commit.

### CODE REVIEW

**Comment by parallelbgls** [comment]
New Sample for Abp.IdentityServer4 for Single Sign-on Server.

**Comment by parallelbgls** [comment]
#https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2214#issuecomment-347420431

**Comment by hikalkan** [comment]
@parallelbgls thank you for your contribution.

This PR is very huge and we can not review it. Can you describe what changes you've done, so we can trust your changes and accept the PR.

**Comment by parallelbgls** [comment]
Thanks, I will push a video to Youtube as soon as possible.

**Comment by parallelbgls** [comment]
IdentityServerDemo

commit: a6c134e

EntityFrameworkCore/IdentityServerDemoDbContext.cs
- Add PersistedGrant

EntityFrameworkCore/IdentityServerDemoEntityFrameworkModule.cs
- Add Abp.IdentityServer4.EntityFrameworkCore Module

JwtTokenMiddleware.cs
- Alter Authentication Scheme to a parameter.

launchSettings.json
- Change port

IdentityServerConfig.cs
- Add Api Resource, Identity Resource and Client by Identity Server 4.

Startup.cs
- Regist IdentityServer4 Server/Client, JwtToken to Owin.
- Add Authentication for Jwt.

test/IdentityServerDemo.ConsoleApiTester/Program.cs
- An Api Tester.

IdentityServerSSODemo

commit: 426010c

All changes modified by IdentityServerDemo

{Api project}
Application/ApiTest/ApiTestAppService.cs
Application/ApiTest/IApiTestAppService.cs
- A test api used in new tester. (Module Zero doesn't exist in Api project)

JwtBearer/JwtTokenMiddleware.cs
- Put Identity Server 4 "sub" claim to Microsoft Identity Claim that ClaimsAbpSession should be recognized.
* (Very important, this is a temporary modification. The reason is that module zero module and identity server 4 module doesn't exist in Api project. ClaimsAbpSeesion will not find user id in Api if programmer duplicate sign server and api server into two websites.
Please find another solution that can replace ClaimsAbpSession in Api).

Configuration/HostingEnvironmentExtensions.cs
Find Application Roots(Module Zero template copied).

launchSettings.json
- Change Port.

SecurityRequirementsOperationFilter.cs
- Authorization Filter for abpsession(Module Zero template copied).

Startup.cs
- Add Authentication for IdentityServer.
- Add Cors(Very important).
- Add Swagger.

appsettings.json
- Add Identity Server Entrypoint.
- Add Cors settings.

other
- Remove Default Two Pages.
- Alter Home page to Swagger Page.

{SSO project}
Startup.cs
- Add Cors(Very important)

appsettings.json
- Alter Cors settings.

IdentityServerDemo.ConsoleApiTester/Program.cs
- Alter Api port.
- Alter Test Api.

**Comment by hikalkan** [comment]
Thank you very much for your detailed explanation.

**Comment by hikalkan** [comment]
@alirizaadiyahsi can you download and test this PR. If it works for us, we will merge it.

**Pull request closed without merging**
