### PR TITLE
Use jquery-serialize-object and bower instead of serializeFormToObject and jquery-extensions.js

### PR DESCRIPTION
**Pull request by gijswijs**
The article claims it uses serializeFormToObject jquery plugin (defined in jquery-extensions.js in the solution).
It does not use this (the Task Create form throws a js error) and bower is used to handle the dependencies.
So I've switched to jquery-serialize-object and bower, and made a small adjustment to the create.js script.
I've added the script to the Create view, but it could also be added to the bundleconfig.json and the _Layout. Both would work.

### CODE REVIEW

**Comment by ismcagdas** [comment]
@gijswijs thank you for your PR. As I checked, jquery-extensions.js is included into layout here https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/master/SimpleTaskSystem-Core/src/Acme.SimpleTaskApp.Web/Views/Shared/_Layout.cshtml#L112. Could you figure out why it is not used ? I haven't tested it by the way.

**Comment by gijswijs** [comment]
Ah, I see. But if you start of with the aspnet-core-template like the article tells you to, the jquery-extensions.js isn't included in the solution. Also the change to _Layout.cshtml isn't explained.
Only if you download the sample application from github (which I didn't) this extra plugin and the different _Layout.cshtml are added to the solution.

So that makes this PR moot (because the solution would work), but the article needs a bit of editing.

**Comment by ismcagdas** [comment]
@gijswijs can you also share the article link ? I want to make sure we are talking about same article 😄

**Comment by gijswijs** [comment]
@ismcagdas Sure, no problem! https://www.codeproject.com/Articles/1117216/Using-ASP-NET-Core-Entity-Framework-Core-and-ASP

It's a great article, by the way. It's so interesting to see how abstract concepts like DTO and Injection suddenly come to live once you actually play around with them.

**Comment by ismcagdas** [comment]
@gijswijs thanks, we are planning to update all of our articles after ABP v3.4 release. So, I'm leaving this issue open to track that.

Thank you for reporting this 😄

**Pull request closed without merging**
